name: Deploy to Minikube

on:
  push:
    branches:
      - master  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          kubeconfig: ${{ secrets.MINIKUBE_KUBE_CONFIG }}

      - name: Deploy to Minikube
        run: |
          kubectl apply -f kubernetes/deployment.yaml
          kubectl apply -f kubernetes/services.yaml
