name: Main Workflow

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Build do aplicação
      - name: Build Docker Image
        uses: ./.github/workflows/build.yaml

      # Deploy da aplicação
      - name: Deploy Application
        uses: ./.github/workflows/deploy.yaml