name: Main Workflow

# Qual branch vai ficar esperado o push.
on:
  push:
    branches:
      - infra-local

jobs:
  build-and-push:
    # Define o ambiente de execução do job (imagem ubuntu)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Construção e Envio da Imagem Docker com a tag do commit
      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/desafio-globo"
          IMAGE_TAG="${{ github.sha }}"

          docker build -t $IMAGE_NAME:$IMAGE_TAG .

          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

          docker push $IMAGE_NAME:$IMAGE_TAG

      # Publicar a imagem com a tag 'latest'
      - name: Publish Latest Image
        run: |
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/desafio-globo"

          docker tag $IMAGE_NAME:${{ github.sha }} $IMAGE_NAME:latest

          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

          docker push $IMAGE_NAME:latest

        # Variáveis de ambiente para o script
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
